// Original video IDs recovered from the published Jupical Healthcare ERP page.
// To update a video later, edit only its youtubeId in the matching section.
export const healthcareSections = [
  {
    number: '01',
    title: 'System Overview & Configuration',
    description: 'HealthPlus is built on Odoo and designed to adapt to your health center from day one. The configuration module lets you define your company profile, set up user roles and permissions, activate the modules you need, and fine tune system parameters all before your first patient walks through the door.',
    bullets: [
      'Set up company profile, logo, and health center details',
      'Define user roles and control staff access levels',
      'Activate modules based on your health center requirements',
      'Configure system-wide parameters for smooth daily operations',
    ],
    youtubeId: 'ettQDXqdlHA',
    image: '/healthcare/section-01.webp',
    icon: 'settings',
  },
  {
    number: '02',
    title: 'Health Center & Building Setup',
    description: 'Map your physical facility into HealthPlus with buildings, wings, and department codes. This structured setup powers everything from patient bed allocation to department routing, making sure every part of your health center is digitally organized and easy to navigate.',
    bullets: [
      'Create and manage multiple buildings and wings',
      'Assign unique codes to each area for identification',
      'Link departments and rooms to specific buildings',
      'Foundation for patient assignments and department routing',
    ],
    youtubeId: 'iYTE3yvYblw',
    image: '/healthcare/section-02.webp',
    icon: 'building',
  },
  {
    number: '03',
    title: 'Doctors & Specializations',
    description: 'Maintain complete profiles for every doctor in your facility from specializations and consultation types to availability and schedules. HealthPlus makes it easy to connect the right specialist to the right patient at the right time.',
    bullets: [
      'Create detailed doctor profiles with contact and specialty info',
      'Define medical specializations and consultation types',
      'Set and manage doctor availability and working hours',
      'Link doctors to departments, buildings, and patient cases',
    ],
    youtubeId: 'PvggM2YIA4Y',
    image: '/healthcare/section-03.webp',
    icon: 'doctor',
  },
  {
    number: '04',
    title: 'Patient Records & Evaluations',
    description: 'From first registration to ongoing care, HealthPlus keeps every patient detail in one place. Staff can register patients, access their full medical history, conduct structured evaluations, and track the complete care journey without switching between systems.',
    bullets: [
      'Register patients with full demographic and contact details',
      'Maintain complete medical history, diagnoses, and prescriptions',
      'Conduct and document evaluations with structured forms',
      'Track patient journey from admission to discharge',
    ],
    youtubeId: 'mKgw_RadXvw',
    image: '/healthcare/section-04.webp',
    icon: 'records',
  },
  {
    number: '05',
    title: 'Surgeries & Procedure Scheduling',
    description: 'Manage the complete surgery lifecycle in one place from request and team assignment to scheduling and status tracking. HealthPlus keeps every surgical operation organized so every team member knows exactly what is happening and when.',
    bullets: [
      'Create surgery requests linked to patient records',
      'Assign surgical teams: surgeons, anaesthetists, and nurses',
      'Schedule procedures with operating room and time slot booking',
      'Track surgery status from request through to completion',
    ],
    youtubeId: '9AmhXGspk84',
    image: '/healthcare/section-05.webp',
    icon: 'surgery',
  },
  {
    number: '06',
    title: 'Imaging & Diagnostics',
    description: 'Handle every medical imaging request from start to finish within HealthPlus. Whether it is a CT scan, X-ray, MRI, or ultrasound, every test is tracked, results are recorded, and reports are linked directly to the patient record.',
    bullets: [
      'Raise imaging requests from doctor or reception',
      'Support for CT, X-Ray, MRI, Ultrasound, and more',
      'Record analysis results and upload diagnostic reports',
      'Link completed imaging tests to patient medical history',
    ],
    youtubeId: 'v1obNJxBoL0',
    image: '/healthcare/section-06.webp',
    icon: 'imaging',
  },
  {
    number: '07',
    title: 'Nursing & Patient Roundings',
    description: 'Give your nursing team a dedicated space to manage patient roundings, care evaluations, and inpatient checklists. HealthPlus ensures nursing workflows are structured, documented, and fully connected to the broader patient care system.',
    bullets: [
      'Create patient rounding records with structured checklists',
      'Track the Seven P\'s assessment for every inpatient',
      'Record vital signs, pain levels, and nursing observations',
      'Link rounding records to patient files for complete documentation',
    ],
    youtubeId: 'pFL1X8uLdL4',
    image: '/healthcare/section-07.webp',
    icon: 'nursing',
  },
  {
    number: '08',
    title: 'Insurance, Pre-Auth & Claims',
    description: 'Take the stress out of insurance with a dedicated workflow for policy capture, pre-authorization, and claims processing. HealthPlus keeps every insurance interaction documented and integrated with patient billing so nothing falls through the cracks.',
    bullets: [
      'Record and manage patient insurance policies and coverage',
      'Submit and track pre-authorization requests before procedures',
      'Process and follow up on insurance claims efficiently',
      'Integrate insurance data with patient billing and invoicing',
    ],
    youtubeId: '1brMiY8iFMg',
    image: '/healthcare/section-08.webp',
    icon: 'insurance',
  },
  {
    number: '09',
    title: 'Doctor Portal & Online Appointments',
    description: 'Doctors get their own web portal where patients can find them and book appointments directly online. Integrated with the HealthPlus scheduling system, the portal keeps both doctors and reception staff in sync with real-time appointment visibility.',
    bullets: [
      'Dedicated web portal for doctors to manage their public profile',
      'Patients can browse available doctors and book online',
      'Real-time appointment visibility for doctors and reception',
      'Integrated with HealthPlus calendar and scheduling system',
    ],
    youtubeId: '15RB3vmExug',
    image: '/healthcare/section-09.webp',
    icon: 'portal',
  },
  {
    number: '10',
    title: 'Patient Portal & Online Appointments',
    description: 'Patients can take control of their own healthcare through a secure self-service web portal. Book and manage appointments, view invoices, and update account details all without calling the clinic.',
    bullets: [
      'Book, reschedule, or cancel appointments online',
      'View and download invoices and billing history',
      'Manage personal account and contact information',
      'Secure individual login for every patient',
    ],
    youtubeId: 'iPppFi_Rk7I',
    image: '/healthcare/section-10.webp',
    icon: 'patient',
  },
  {
    number: '11',
    title: 'Mobile App for Doctors',
    description: 'Doctors can stay connected to their practice from anywhere with the HealthPlus mobile app. Check appointments, update patient records, track inpatient cases, and manage surgeries all from a smartphone.',
    bullets: [
      'View today\'s appointments and upcoming schedule instantly',
      'Access and update patient records and evaluations on the go',
      'Track inpatient records and patients currently under care',
      'Manage assigned surgeries from the mobile interface',
    ],
    youtubeId: 'uE_oEjIJNFM',
    image: '/healthcare/section-11.webp',
    icon: 'mobile',
  },
  {
    number: '12',
    title: 'Mobile App for Patients',
    description: 'Put healthcare in every patient\'s pocket. The HealthPlus patient mobile app makes it easy to book appointments, track health records, and stay connected with the health center all from a smartphone.',
    bullets: [
      'Secure login with individual patient credentials',
      'Book and manage appointments from mobile',
      'Access personal health records and visit history',
      'Stay connected and informed with the health center',
    ],
    youtubeId: 'KOs1DULLhK8',
    image: '/healthcare/section-12.webp',
    icon: 'mobile',
  },
];

// Preserve the original YouTube embed URL format used by the source page.
export const healthcareVideoUrl = (youtubeId) => `https://www.youtube.com/embed/${youtubeId}?rel=0&autoplay=0`;
